name: CET Production Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy to VPS
        run: |
          cd /var/www/cet/CET
          git fetch --all
          git reset --hard origin/main
          docker compose up -d --build --remove-orphans
          docker image prune -f
